import type { PropertyAssets } from './types'

// Generated from the old site's gloch-tower page. Files live in /public/portfolio/gloch-tower/
export const glochTowerAssets: PropertyAssets = {
  descriptionImage: '/portfolio/gloch-tower/interior/gloch23.jpg',
  brochures: [
    { label: 'Download Penthouse Brochure', href: '/portfolio/gloch-tower/brochures/Penthouses-Iconic-Gloch-Tower_5_28-2.pdf' },
    { label: 'Download Brochure', href: '/portfolio/gloch-tower/brochures/THE-ICONIC-GLOCH-TOWER1.pdf' },
  ],
  gallery: {
    exterior: [
      '/portfolio/gloch-tower/exterior/gloch03.jpg',
      '/portfolio/gloch-tower/exterior/gloch01.webp',
      '/portfolio/gloch-tower/exterior/gloch02.jpg',
      '/portfolio/gloch-tower/exterior/gloch01-main.png',
    ],
    interior: [
      '/portfolio/gloch-tower/interior/gloch21.jpg',
      '/portfolio/gloch-tower/interior/gloch4.jpg',
      '/portfolio/gloch-tower/interior/gloch12.jpg',
      '/portfolio/gloch-tower/interior/gloch20.jpg',
      '/portfolio/gloch-tower/interior/gloch7.jpg',
      '/portfolio/gloch-tower/interior/gloch25.jpg',
      '/portfolio/gloch-tower/interior/gloch5.jpg',
      '/portfolio/gloch-tower/interior/gloch27.jpg',
      '/portfolio/gloch-tower/interior/gloch14.jpg',
      '/portfolio/gloch-tower/interior/gloch23.jpg',
      '/portfolio/gloch-tower/interior/gloch17.jpg',
      '/portfolio/gloch-tower/interior/gloch8.jpg',
      '/portfolio/gloch-tower/interior/gloch26.jpg',
      '/portfolio/gloch-tower/interior/gloch19.jpg',
      '/portfolio/gloch-tower/interior/gloch3.jpg',
      '/portfolio/gloch-tower/interior/gloch9.jpg',
      '/portfolio/gloch-tower/interior/gloch22.jpg',
      '/portfolio/gloch-tower/interior/gloch11.jpg',
      '/portfolio/gloch-tower/interior/gloch24.jpg',
      '/portfolio/gloch-tower/interior/gloch10.jpg',
      '/portfolio/gloch-tower/interior/gloch13.jpg',
      '/portfolio/gloch-tower/interior/gloch18.jpg',
      '/portfolio/gloch-tower/interior/gloch6.jpg',
      '/portfolio/gloch-tower/interior/gloch1.jpg',
      '/portfolio/gloch-tower/interior/gloch16.jpg',
      '/portfolio/gloch-tower/interior/gloch15.jpg',
      '/portfolio/gloch-tower/interior/gloch2.jpg',
    ],
    siteUpdate: [
      '/portfolio/gloch-tower/site-update/gloch-sitemap02.jpg',
      '/portfolio/gloch-tower/site-update/gloch-sitemap20.jpg',
      '/portfolio/gloch-tower/site-update/gloch-sitemap03.jpg',
      '/portfolio/gloch-tower/site-update/gloch-sitemap07.jpg',
      '/portfolio/gloch-tower/site-update/gloch-sitemap22.jpg',
      '/portfolio/gloch-tower/site-update/gloch-sitemap19.jpg',
      '/portfolio/gloch-tower/site-update/gloch-sitemap23.jpg',
      '/portfolio/gloch-tower/site-update/gloch-sitemap15.jpg',
      '/portfolio/gloch-tower/site-update/gloch-sitemap09.jpg',
      '/portfolio/gloch-tower/site-update/gloch-sitemap04.jpg',
      '/portfolio/gloch-tower/site-update/gloch-sitemap05.jpg',
      '/portfolio/gloch-tower/site-update/gloch-sitemap10.jpg',
      '/portfolio/gloch-tower/site-update/gloch-sitemap13.jpg',
      '/portfolio/gloch-tower/site-update/gloch-sitemap16.jpg',
      '/portfolio/gloch-tower/site-update/gloch-sitemap06.jpg',
      '/portfolio/gloch-tower/site-update/gloch-sitemap14.jpg',
      '/portfolio/gloch-tower/site-update/gloch-sitemap12.jpg',
      '/portfolio/gloch-tower/site-update/gloch-sitemap18.jpg',
      '/portfolio/gloch-tower/site-update/gloch-sitemap21.jpg',
      '/portfolio/gloch-tower/site-update/gloch-sitemap17.jpg',
      '/portfolio/gloch-tower/site-update/gloch-sitemap01.jpg',
      '/portfolio/gloch-tower/site-update/gloch-sitemap11.jpg',
    ],
  },
}